export interface EmojiItem {
  emoji: string;
  keywords: string[];
}

export const emojiList: EmojiItem[] = [
  { emoji: '🍇', keywords: ['grapes', 'fruit', 'uvas', 'fruta', 'raisins', 'trauben', 'obst', 'uva'] },
  { emoji: '🍈', keywords: ['melon', 'fruit', 'melón', 'fruta', 'melon', 'melone', 'melone'] },
  { emoji: '🍉', keywords: ['watermelon', 'fruit', 'sandía', 'fruta', 'pastèque', 'wassermelone', 'anguria'] },
  { emoji: '🍊', keywords: ['tangerine', 'orange', 'fruit', 'mandarina', 'naranja', 'fruta', 'mandarine', 'mandarine', 'mandarino'] },
  { emoji: '🍋', keywords: ['lemon', 'fruit', 'limón', 'fruta', 'citron', 'zitrone', 'limone'] },
  { emoji: '🍌', keywords: ['banana', 'fruit', 'plátano', 'banana', 'fruta', 'banane', 'banane', 'banana'] },
  { emoji: '🍍', keywords: ['pineapple', 'fruit', 'piña', 'fruta', 'ananas', 'ananas', 'ananas'] },
  { emoji: '🥭', keywords: ['mango', 'fruit', 'mango', 'fruta', 'mangue', 'mango', 'mango'] },
  { emoji: '🍎', keywords: ['apple', 'red apple', 'fruit', 'manzana', 'roja', 'fruta', 'pomme', 'rouge', 'apfel', 'rot', 'mela', 'rossa'] },
  { emoji: '🍏', keywords: ['green apple', 'apple', 'fruit', 'manzana', 'verde', 'fruta', 'pomme', 'verte', 'apfel', 'grün', 'mela', 'verde'] },
  { emoji: '🍐', keywords: ['pear', 'fruit', 'pera', 'fruta', 'poire', 'birne', 'pera'] },
  { emoji: '🍑', keywords: ['peach', 'fruit', 'melocotón', 'durazno', 'fruta', 'pêche', 'pfirsich', 'pesca'] },
  { emoji: '🍒', keywords: ['cherries', 'fruit', 'cerezas', 'fruta', 'cerises', 'kirschen', 'ciliegie'] },
  { emoji: '🍓', keywords: ['strawberry', 'fruit', 'fresa', 'frutilla', 'fruta', 'fraise', 'erdbeere', 'fragola'] },
  { emoji: '🥝', keywords: ['kiwi', 'fruit', 'kiwi', 'fruta', 'kiwi', 'kiwi', 'kiwi'] },
  { emoji: '🍅', keywords: ['tomato', 'vegetable', 'tomate', 'vegetal', 'tomate', 'tomate', 'pomodoro'] },
  { emoji: '🫒', keywords: ['olive', 'oliva', 'aceituna', 'olive', 'olive', 'oliva'] },
  { emoji: '🥥', keywords: ['coconut', 'fruit', 'coco', 'fruta', 'noix de coco', 'kokosnuss', 'cocco'] },

  { emoji: '🥑', keywords: ['avocado', 'vegetable', 'aguacate', 'palta', 'mod', 'avocat', 'avocado', 'avocado'] },
  { emoji: '🍆', keywords: ['eggplant', 'vegetable', 'berenjena', 'vegetal', 'aubergine', 'aubergine', 'melanzana'] },
  { emoji: '🥔', keywords: ['potato', 'vegetable', 'patata', 'papa', 'vegetal', 'pomme de terre', 'kartoffel', 'patata'] },
  { emoji: '🥕', keywords: ['carrot', 'vegetable', 'zanahoria', 'vegetal', 'carotte', 'karotte', 'carota'] },
  { emoji: '🌽', keywords: ['corn', 'vegetable', 'maíz', 'choclo', 'elote', 'maïs', 'mais', 'mais'] },
  { emoji: '🌶️', keywords: ['hot pepper', 'chili', 'spicy', 'chile', 'picante', 'piment', 'peperoni', 'peperoncino'] },
  { emoji: '🥒', keywords: ['cucumber', 'vegetable', 'pepino', 'vegetal', 'concombre', 'gurke', 'cetriolo'] },
  { emoji: '🥬', keywords: ['leafy green', 'lettuce', 'vegetable', 'lechuga', 'verdura', 'laitue', 'salat', 'lattuga'] },
  { emoji: '🥦', keywords: ['broccoli', 'vegetable', 'brócoli', 'vegetal', 'brocoli', 'brokkoli', 'broccoli'] },
  { emoji: '🧄', keywords: ['garlic', 'ajo', 'ail', 'knoblauch', 'aglio'] },
  { emoji: '🧅', keywords: ['onion', 'cebolla', 'oignon', 'zwiebel', 'cipolla'] },
  { emoji: '🍄', keywords: ['mushroom', 'fungus', 'hongo', 'seta', 'champiñón', 'champignon', 'pilz', 'fungo'] },
  { emoji: '🥜', keywords: ['peanuts', 'nut', 'cacahuetes', 'maní', 'cacahuètes', 'erdnüsse', 'arachidi'] },
  { emoji: '🌰', keywords: ['chestnut', 'nut', 'castaña', 'châtaigne', 'kastanie', 'castagna'] },

  { emoji: '🍞', keywords: ['bread', 'pan', 'pain', 'brot', 'pane'] },
  { emoji: '🥐', keywords: ['croissant', 'pastry', 'croissant', 'croissant', 'croissant', 'cornetto'] },
  { emoji: '🥖', keywords: ['baguette', 'bread', 'baguette', 'barra', 'baguette', 'baguette', 'baguette'] },
  { emoji: '🫓', keywords: ['flatbread', 'pan plano', 'pain plat', 'fladenbrot', 'pane piatto'] },
  { emoji: '🥨', keywords: ['pretzel', 'snack', 'bretzel', 'bretzel', 'brezel', 'bretzel'] },
  { emoji: '🥯', keywords: ['bagel', 'bread', 'bagel', 'bagel', 'bagel', 'bagel'] },
  { emoji: '🥞', keywords: ['pancakes', 'hotcakes', 'tortitas', 'panqueques', 'pancakes', 'pfannkuchen', 'pancake'] },
  { emoji: '🧀', keywords: ['cheese', 'wedge', 'queso', 'fromage', 'käse', 'formaggio'] },
  { emoji: '🍖', keywords: ['meat on bone', 'meat', 'carne', 'hueso', 'viande', 'fleisch', 'carne'] },
  { emoji: '🍗', keywords: ['poultry leg', 'chicken', 'pollo', 'pierna', 'poulet', 'hähnchen', 'pollo'] },
  { emoji: '🥩', keywords: ['cut of meat', 'steak', 'carne', 'filete', 'bistec', 'viande', 'steak', 'fleisch', 'carne', 'bistecca'] },
  { emoji: '🥓', keywords: ['bacon', 'meat', 'tocino', 'panceta', 'bacon', 'speck', 'pancetta'] },
  { emoji: '🍔', keywords: ['hamburger', 'burger', 'fast food', 'hamburguesa', 'hamburger', 'hamburger', 'hamburger'] },
  { emoji: '🍟', keywords: ['french fries', 'fries', 'chips', 'papas fritas', 'patatas fritas', 'frites', 'pommes', 'patatine'] },
  { emoji: '🍕', keywords: ['pizza', 'food', 'pizza', 'pizza', 'pizza', 'pizza'] },
  { emoji: '🌭', keywords: ['hot dog', 'frankfurter', 'hot dog', 'perrito caliente', 'hot-dog', 'hotdog', 'hot dog'] },
  { emoji: '🥪', keywords: ['sandwich', 'food', 'sándwich', 'bocadillo', 'sandwich', 'sandwich', 'sandwich'] },
  { emoji: '🌮', keywords: ['taco', 'mexican', 'taco', 'taco', 'taco', 'taco'] },
  { emoji: '🌯', keywords: ['burrito', 'wrap', 'mexican', 'burrito', 'burrito', 'burrito', 'burrito'] },
  { emoji: '🥙', keywords: ['stuffed flatbread', 'kebab', 'pita', 'pan de pita', 'kebab', 'pita', 'döner', 'kebab'] },
  { emoji: '🥚', keywords: ['egg', 'food', 'huevo', 'œuf', 'ei', 'uovo'] },
  { emoji: '🍳', keywords: ['cooking', 'fried egg', 'pan', 'cocinar', 'huevo frito', 'sartén', 'cuisine', 'œuf sur le plat', 'poêle', 'kochen', 'spiegelei', 'pfanne', 'cucinare', 'uovo fritto', 'padella'] },
  { emoji: '🥘', keywords: ['shallow pan of food', 'paella', 'casserole', 'paella', 'cazuela', 'poêlée', 'pfannengericht', 'paella'] },
  { emoji: '🍲', keywords: ['pot of food', 'stew', 'soup', 'estofado', 'sopa', 'ragoût', 'soupe', 'eintopf', 'suppe', 'stufato', 'zuppa'] },
  { emoji: '🫕', keywords: ['fondue', 'fondue', 'fondue', 'fondue', 'fonduta'] },
  { emoji: '🥣', keywords: ['bowl with spoon', 'cereal', 'soup', 'tazón', 'cereal', 'sopa', 'bol', 'céréales', 'schüssel', 'müsli', 'ciotola', 'cereali'] },
  { emoji: '🥗', keywords: ['green salad', 'salad', 'healthy', 'ensalada', 'salade', 'salat', 'insalata'] },
  { emoji: '🍿', keywords: ['popcorn', 'snack', 'palomitas', 'pop-corn', 'popcorn', 'popcorn'] },
  { emoji: '🧂', keywords: ['salt', 'seasoning', 'sal', 'sel', 'salz', 'sale'] },
  { emoji: '🥫', keywords: ['canned food', 'can', 'comida en lata', 'lata', 'conserve', 'dose', 'cibo in scatola'] },

  { emoji: '🍱', keywords: ['bento box', 'lunch', 'bento', 'caja de almuerzo', 'bento', 'bento', 'bento'] },
  { emoji: '🍙', keywords: ['rice ball', 'onigiri', 'bola de arroz', 'onigiri', 'boulette de riz', 'reisbällchen', 'palla di riso'] },
  { emoji: '🍚', keywords: ['cooked rice', 'rice', 'arroz cocido', 'arroz', 'riz cuit', 'riz', 'gekochter reis', 'reis', 'riso cotto', 'riso'] },
  { emoji: '🍛', keywords: ['curry rice', 'curry', 'arroz con curry', 'curry', 'riz au curry', 'curryreis', 'riso al curry'] },
  { emoji: '🍜', keywords: ['steaming bowl', 'ramen', 'noodles', 'fideos', 'ramen', 'nouilles', 'nudeln', 'ramen'] },
  { emoji: '🍝', keywords: ['spaghetti', 'pasta', 'espaguetis', 'pasta', 'spaghetti', 'spaghetti', 'spaghetti'] },
  { emoji: '🍠', keywords: ['roasted sweet potato', 'sweet potato', 'batata', 'boniato', 'camote', 'patate douce', 'süßkartoffel', 'patata dolce'] },
  { emoji: '🍢', keywords: ['oden', 'skewer', 'oden', 'brocheta', 'oden', 'oden', 'oden'] },
  { emoji: '🍣', keywords: ['sushi', 'fish', 'sushi', 'pescado', 'sushi', 'sushi', 'sushi'] },
  { emoji: '🍤', keywords: ['fried shrimp', 'shrimp', 'tempura', 'gamba frita', 'camarón', 'crevette frite', 'frittierte garnele', 'gambero fritto'] },
  { emoji: '🍥', keywords: ['fish cake', 'naruto', 'pastel de pescado', 'gâteau de poisson', 'fischfrikadelle', 'tortino di pesce'] },
  { emoji: '🥮', keywords: ['moon cake', 'festival', 'pastel de luna', 'gâteau de lune', 'mondkuchen', 'torta lunare'] },
  { emoji: '🍡', keywords: ['dango', 'sweet', 'dango', 'dulce', 'dango', 'dango', 'dango'] },
  { emoji: '🥟', keywords: ['dumpling', 'empanada', 'bollo', 'dumpling', 'teigtasche', 'gnocco'] },
  { emoji: '🥠', keywords: ['fortune cookie', 'cookie', 'galleta de la fortuna', 'biscuit chinois', 'glückskeks', 'biscotto della fortuna'] },
  { emoji: '🥡', keywords: ['takeout box', 'food', 'caja de comida', 'para llevar', 'boîte à emporter', 'take-away-box', 'scatola da asporto'] },

  { emoji: '🦀', keywords: ['crab', 'seafood', 'cangrejo', 'marisco', 'crabe', 'krabbe', 'granchio'] },
  { emoji: '🦞', keywords: ['lobster', 'seafood', 'langosta', 'bogavante', 'homard', 'hummer', 'aragosta'] },
  { emoji: '🦐', keywords: ['shrimp', 'seafood', 'camarón', 'gamba', 'crevette', 'garnele', 'gambero'] },
  { emoji: '🦑', keywords: ['squid', 'seafood', 'calamar', 'calmar', 'tintenfisch', 'calamaro'] },
  { emoji: '🦪', keywords: ['oyster', 'ostras', 'huître', 'auster', 'ostrica'] },

  { emoji: '🍦', keywords: ['soft ice cream', 'ice cream', 'helado suave', 'glace à l\'italienne', 'softeis', 'gelato soft'] },
  { emoji: '🍧', keywords: ['shaved ice', 'dessert', 'granizado', 'raspado', 'glace pilée', 'wassereis', 'granita'] },
  { emoji: '🍨', keywords: ['ice cream', 'dessert', 'helado', 'copa de helado', 'glace', 'eiscreme', 'gelato'] },
  { emoji: '🍩', keywords: ['doughnut', 'donut', 'rosquilla', 'donut', 'beignet', 'donught', 'ciambella'] },
  { emoji: '🍪', keywords: ['cookie', 'biscuit', 'galleta', 'biscuit', 'keks', 'biscotto'] },
  { emoji: '🎂', keywords: ['birthday cake', 'cake', 'pastel', 'tarta', 'cumpleaños', 'gâteau d\'anniversaire', 'geburtstagstorte', 'torta di compleanno'] },
  { emoji: '🍰', keywords: ['shortcake', 'cake', 'slice', 'pastel', 'trozo', 'gâteau', 'torte', 'torta'] },
  { emoji: '🧁', keywords: ['cupcake', 'muffin', 'magdalena', 'cupcake', 'cupcake', 'cupcake', 'cupcake'] },
  { emoji: '🥧', keywords: ['pie', 'pastry', 'pastel', 'tarta', 'tarte', 'pastete', 'torta'] },
  { emoji: '🍫', keywords: ['chocolate bar', 'chocolate', 'chocolate', 'barrita', 'chocolat', 'schokolade', 'cioccolato'] },
  { emoji: '🍬', keywords: ['candy', 'sweet', 'caramelo', 'dulce', 'bonbon', 'bonbon', 'caramella'] },
  { emoji: '🍭', keywords: ['lollipop', 'candy', 'piruleta', 'chupachups', 'sucette', 'lutscher', 'lecca lecca'] },
  { emoji: '🍮', keywords: ['custard', 'flan', 'pudding', 'flan', 'crème caramel', 'pudding', 'budino'] },
  { emoji: '🍯', keywords: ['honey pot', 'honey', 'miel', 'tarro', 'miel', 'honig', 'miele'] },

  { emoji: '🥛', keywords: ['glass of milk', 'milk', 'vaso de leche', 'leche', 'verre de lait', 'milch', 'bicchiere di latte'] },
  { emoji: '🍼', keywords: ['baby bottle', 'milk', 'biberón', 'leche', 'biberon', 'babyflasche', 'biberon'] },
  { emoji: '☕', keywords: ['hot beverage', 'coffee', 'tea', 'bebida caliente', 'café', 'té', 'boisson chaude', 'heißgetränk', 'bevanda calda'] },
  { emoji: '🫖', keywords: ['teapot', 'tea', 'tetera', 'théière', 'teekanne', 'teiera'] },
  { emoji: '🍵', keywords: ['teacup without handle', 'tea', 'matcha', 'taza de té', 'té', 'tasse de thé', 'teetasse', 'tazza di tè'] },
  { emoji: '🍶', keywords: ['sake', 'bottle', 'sake', 'saké', 'sake', 'sake'] },
  { emoji: '🍾', keywords: ['champagne', 'bottle', 'champán', 'botella', 'champagne', 'shampus', 'champagne'] },
  { emoji: '🍷', keywords: ['wine glass', 'wine', 'vino', 'copa', 'vin', 'wein', 'vino'] },
  { emoji: '🍸', keywords: ['cocktail glass', 'cocktail', 'cóctel', 'copa', 'cocktail', 'cocktail', 'cocktail'] },
  { emoji: '🍹', keywords: ['tropical drink', 'cocktail', 'bebida tropical', 'cóctel', 'boisson tropicale', 'tropischer drink', 'bevanda tropicale'] },
  { emoji: '🍺', keywords: ['beer mug', 'beer', 'cerveza', 'jarra', 'bière', 'bier', 'birra'] },
  { emoji: '🍻', keywords: ['clinking beer mugs', 'cheers', 'beer', 'brindis', 'cerveza', 'chope', 'prost', 'salute'] },
  { emoji: '🥂', keywords: ['clinking glasses', 'cheers', 'champagne', 'brindis', 'copas', 'trinquer', 'prost', 'cin cin'] },
  { emoji: '🥃', keywords: ['tumbler glass', 'whisky', 'vaso', 'whisky', 'verre', 'whisky', 'bicchiere'] },
  { emoji: '🫗', keywords: ['pouring liquid', 'drink', 'spill', 'vertido', 'derrame', 'verser', 'liquide', 'eingießen', 'verschütten', 'versare', 'liquido'] },
  { emoji: '🥤', keywords: ['cup with straw', 'soda', 'drink', 'vaso con pajita', 'refresco', 'gobelet', 'becher', 'bicchiere con cannuccia'] },
  { emoji: '🧋', keywords: ['bubble tea', 'boba', 'milk tea', 'té de burbujas', 'thé aux perles', 'bubble tea', 'tè con le bolle'] },
  { emoji: '🧃', keywords: ['beverage box', 'juice', 'jugo', 'zumo', 'caja de jugo', 'jus', 'saft', 'succo'] },
  { emoji: '🧉', keywords: ['mate', 'drink', 'mate', 'yerba', 'maté', 'mate', 'mate'] },
  { emoji: '🧊', keywords: ['ice', 'cube', 'hielo', 'cubito', 'glace', 'eisunrfel', 'ghiaccio'] },
  { emoji: '🫙', keywords: ['jar', 'container', 'food', 'tarro', 'bote', 'bocal', 'glas', 'barattolo'] },

  { emoji: '🥢', keywords: ['chopsticks', 'utensils', 'palillos', 'baguettes', 'essstäbchen', 'bacchette'] },
  { emoji: '🍽️', keywords: ['fork and knife with plate', 'dining', 'plato', 'cubiertos', 'assiette', 'teller', 'piatto'] },
  { emoji: '🍴', keywords: ['fork and knife', 'cutlery', 'tenedor y cuchillo', 'cubiertos', 'fourchette et couteau', 'besteck', 'forchetta e coltello'] },
  { emoji: '🥄', keywords: ['spoon', 'cutlery', 'cuchara', 'cuillère', 'löffel', 'cucchiaio'] },
  { emoji: '🔪', keywords: ['kitchen knife', 'knife', 'cuchillo', 'couteau', 'messer', 'coltello'] },
  { emoji: '🏺', keywords: ['amphora', 'jar', 'anfora', 'ánfora', 'amphore', 'amphore', 'anfora'] },

  { emoji: '🐮', keywords: ['cow', 'beef', 'animal', 'vaca', 'ternera', 'vache', 'bœuf', 'kuh', 'rind', 'mucca', 'manzo'] },
  { emoji: '🐷', keywords: ['pig', 'pork', 'animal', 'cerdo', 'puerco', 'cochon', 'porc', 'schwein', 'maiale'] },
  { emoji: '🐑', keywords: ['sheep', 'lamb', 'animal', 'oveja', 'cordero', 'mouton', 'agneau', 'schaf', 'lamm', 'pecora', 'agnello'] },
  { emoji: '🐇', keywords: ['rabbit', 'animal', 'conejo', 'lapin', 'hase', 'kaninchen', 'coniglio'] },
  { emoji: '🦃', keywords: ['turkey', 'bird', 'animal', 'pavo', 'dinde', 'truthahn', 'tacchino'] },
  { emoji: '🐔', keywords: ['chicken', 'hen', 'bird', 'animal', 'pollo', 'gallina', 'poulet', 'poule', 'huhn', 'pollo', 'gallina'] },
  { emoji: '🦆', keywords: ['duck', 'bird', 'animal', 'pato', 'canard', 'ente', 'anatra'] },
  { emoji: '🪿', keywords: ['goose', 'bird', 'animal', 'ganso', 'oie', 'gans', 'oca'] },
  { emoji: '🐟', keywords: ['fish', 'animal', 'pescado', 'pez', 'poisson', 'fisch', 'pesce'] },
  { emoji: '🐠', keywords: ['tropical fish', 'fish', 'animal', 'pez tropical', 'poisson tropical', 'tropenfisch', 'pesce tropicale'] },
  { emoji: '🐡', keywords: ['blowfish', 'fish', 'animal', 'pez globo', 'poisson-globe', 'kugelfisch', 'pesce palla'] },
  { emoji: '🐙', keywords: ['octopus', 'animal', 'pulpo', 'pieuvre', 'poulpe', 'oktopus', 'krake', 'polpo'] },
  { emoji: '🐚', keywords: ['spiral shell', 'shellfish', 'animal', 'concha', 'caracola', 'coquillage', 'schneckenhaus', 'conchiglia'] },
  { emoji: '🐌', keywords: ['snail', 'escargot', 'animal', 'caracol', 'escargot', 'schnecke', 'lumaca'] },
];

export const utilityEmojiList: EmojiItem[] = [
  { emoji: '🤤', keywords: ['drooling'] },
  { emoji: '😴', keywords: ['sleeping'] },
  { emoji: '😫', keywords: ['weary'] },
  { emoji: '🔥', keywords: ['fire'] },
  { emoji: '🔍', keywords: ['search'] },
  { emoji: '📏', keywords: ['ruler'] },
  { emoji: '💪', keywords: ['strong'] },
  { emoji: '👤', keywords: ['user'] },
  { emoji: '👣', keywords: ['footprints'] },
  { emoji: '🏠', keywords: ['home'] },
  { emoji: '🏃', keywords: ['running'] },
  { emoji: '❌', keywords: ['cancel'] },
  { emoji: '⚡', keywords: ['lightning'] },
  { emoji: '⚠️', keywords: ['warning'] },
  { emoji: '⚖️', keywords: ['balance'] },
  { emoji: '🪫', keywords: ['battery'] },
  { emoji: '✏️', keywords: ['pencil'] }
];
